baseURL = 'http://example.org/'
languageCode = 'ko-kr'
title = '블로그'
theme = 'holy'
publishDir = "docs"


[params]
  copyright = "Copyright © 2023, jenna1030, powered by Hugo, themed from holy"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "소개"
    url = "/about/"
    weight = 10


